[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_dark.toml"
]

[terminal.shell]
program = "tmux"

[font]
normal = { family = "JetbrainsMono Nerd Font", style="regular"}
size = 14

[window]
opacity = 0.7
