# vim:ft=kitty
## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground                      #e0def4
background                      #191724
selection_foreground            #e0def4
selection_background            #403d52

cursor                          #524f67
cursor_text_color               #e0def4

url_color                       #c4a7e7

active_border_color             #c4a7e7
inactive_border_color           #26233a
bell_border_color               #eb6f92
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #191724
active_tab_foreground           #e0def4
inactive_tab_background         #1f1d2e
inactive_tab_foreground         #6e6a86
tab_bar_background              #1f1d2e
tab_bar_margin_color            none

mark1_foreground                #191724
mark1_background                #c4a7e7
mark2_foreground                #191724
mark2_background                #9ccfd8
mark3_foreground                #191724
mark3_background                #eb6f92

#: black
color0                          #26233a
color8                          #6e6a86

#: red (love)
color1                          #eb6f92
color9                          #eb6f92

#: green (pine)
color2                          #31748f
color10                         #31748f

#: yellow (gold)
color3                          #f6c177
color11                         #f6c177

#: blue (foam)
color4                          #9ccfd8
color12                         #9ccfd8

#: magenta (iris)
color5                          #c4a7e7
color13                         #c4a7e7

#: cyan (rose)
color6                          #ebbcba
color14                         #ebbcba

#: white
color7                          #e0def4
color15                         #e0def4
