# vim:ft=kitty
## name: City Lights
## author: Yummygum
## license: MIT
## upstream: https://citylights.xyz
## blurb: A dark matte theme inspired by neon city nights

foreground                      #b7c5d3
background                      #1d252c
selection_foreground            #b7c5d3
selection_background            #28323a

cursor                          #5ec4ff
cursor_text_color               #1d252c

url_color                       #539afc

active_border_color             #5ec4ff
inactive_border_color           #333f4a
bell_border_color               #e27e8d
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #1d252c
active_tab_foreground           #b7c5d3
inactive_tab_background         #181e24
inactive_tab_foreground         #41505e
tab_bar_background              #181e24
tab_bar_margin_color            none

mark1_foreground                #1d252c
mark1_background                #5ec4ff
mark2_foreground                #1d252c
mark2_background                #8bd49c
mark3_foreground                #1d252c
mark3_background                #e27e8d

#: black
color0                          #333f4a
color8                          #41505e

#: red
color1                          #d95468
color9                          #e27e8d

#: green
color2                          #8bd49c
color10                         #8bd49c

#: yellow
color3                          #d98e48
color11                         #ebbf83

#: blue
color4                          #539afc
color12                         #5ec4ff

#: magenta
color5                          #e27e8d
color13                         #b62d65

#: cyan
color6                          #008b94
color14                         #70e1e8

#: white
color7                          #718ca1
color15                         #b7c5d3
