# vim:ft=kitty
## name: Gruvbox Dark Hard
## author: morhetz
## license: MIT
## upstream: https://github.com/morhetz/gruvbox
## blurb: Retro groove colors with hard dark contrast

foreground                      #ebdbb2
background                      #1d2021
selection_foreground            #ebdbb2
selection_background            #504945

cursor                          #ebdbb2
cursor_text_color               #1d2021

url_color                       #83a598

active_border_color             #d79921
inactive_border_color           #3c3836
bell_border_color               #cc241d
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #1d2021
active_tab_foreground           #ebdbb2
inactive_tab_background         #282828
inactive_tab_foreground         #a89984
tab_bar_background              #1d2021
tab_bar_margin_color            none

mark1_foreground                #1d2021
mark1_background                #83a598
mark2_foreground                #1d2021
mark2_background                #ebdbb2
mark3_foreground                #1d2021
mark3_background                #d3869b

#: black
color0                          #282828
color8                          #928374

#: red
color1                          #cc241d
color9                          #fb4934

#: green
color2                          #98971a
color10                         #b8bb26

#: yellow
color3                          #d79921
color11                         #fabd2f

#: blue
color4                          #458588
color12                         #83a598

#: magenta
color5                          #b16286
color13                         #d3869b

#: cyan
color6                          #689d6a
color14                         #8ec07c

#: white
color7                          #a89984
color15                         #ebdbb2
