# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using | and -
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# start window and pane numbers at 1
set -g base-index 1
set -g pane-base-index 1

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# resize panes using vim keys (repeatable)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# DESIGN TWEAKS

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour '#d79921'

# copy mode
setw -g mode-keys vi
setw -g mode-style 'fg=#1d2021 bg=#cc241d bold'
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

# panes
set -g pane-border-style 'fg=#3c3836'
set -g pane-active-border-style 'fg=#d79921'

# statusbar
set -g status-position top
set -g status-justify left
set -g status-style 'fg=#ebdbb2 bg=#1d2021'

set -g status-left-style 'fg=#1d2021 bg=#d79921'
set -g status-left ' #S #[fg=#d79921,bg=#504945]#[fg=#ebdbb2,bg=#504945]  #(cd #{pane_current_path} && git branch --show-current 2>/dev/null || echo "") '
set -g status-left-length 80

set -g status-right-style 'fg=#ebdbb2 bg=#1d2021'
set -g status-right '#[fg=#1d2021,bg=#b16286] #(~/dotfiles/scripts/weather.sh) #[fg=#1d2021,bg=#98971a]  #(top -l 1 | grep -E "^CPU" | awk "{print 100 - \$7}")%% #[fg=#1d2021,bg=#458588] 󰘚 #(~/dotfiles/scripts/ram_usage.sh) #[fg=#1d2021,bg=#d79921] 󰃰 %b/%d '
set -g status-right-length 200
set -g status-interval 5

setw -g window-status-current-style 'fg=#1d2021 bg=#cc241d'
setw -g window-status-current-format ' #I #W #F '

setw -g window-status-style 'fg=#a89984 bg=#1d2021'
setw -g window-status-format ' #I #[fg=#ebdbb2]#W #[fg=#d79921]#F '

setw -g window-status-bell-style 'fg=#d79921 bg=#cc241d bold'

# messages
set -g message-style 'fg=#d79921 bg=#cc241d bold'

# terminal + truecolor support
set -g default-terminal "tmux-256color"
set -as terminal-features ',xterm-256color:RGB,tmux-256color:RGB,screen-256color:RGB'
