config_version = 14

[bar.default]
background_opacity = 0.669999985024333
center = [ "clock", "media" ]
concave_edge_corners = false
end = [
    "notifications",
    "launcher",
    "tray",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
font_family = "Iosevka NF"
margin_ends = 0
radius = 0
start = [ "workspaces" ]

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 538.0
    output = "eDP-1"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[shell]
panel_anchor_bar = "default"

    [shell.screen_corners]
    size = 1

    [shell.window_switcher]
    style = "compact"

[theme]
source = "wallpaper"

[wallpaper]
directory = "/home/arjun/Pictures/walls"

    [wallpaper.default]
    path = "/home/arjun/Pictures/walls/japanese_pedestrian_street.png"

    [wallpaper.last]
    path = "/home/arjun/Pictures/walls/japanese_pedestrian_street.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/arjun/Pictures/walls/japanese_pedestrian_street.png"

[widget.media]
hide_when_no_media = true

[widget.network]
show_label = false
