# City Lights
# Author: Yummygum
# Source: https://citylights.xyz

[colors.primary]
background = '#1d252c'
foreground = '#b7c5d3'

[colors.cursor]
text   = '#1d252c'
cursor = '#5ec4ff'

[colors.selection]
text       = '#b7c5d3'
background = '#28323a'

[colors.normal]
black   = '#333f4a'
red     = '#d95468'
green   = '#8bd49c'
yellow  = '#d98e48'
blue    = '#539afc'
magenta = '#e27e8d'
cyan    = '#008b94'
white   = '#718ca1'

[colors.bright]
black   = '#41505e'
red     = '#e27e8d'
green   = '#8bd49c'
yellow  = '#ebbf83'
blue    = '#5ec4ff'
magenta = '#b62d65'
cyan    = '#70e1e8'
white   = '#b7c5d3'
