theme = "city_lights"

[editor]
line-number = "relative"
mouse = false
soft-wrap.enable = true
auto-format = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
